services:
  surat-franken:
    container_name: surat-franken
    restart: unless-stopped
    environment:
      - SERVER_NAME=:80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.env:/app/.env
      - storage_data:/app/storage
    networks:
      - default
      - mysql-stack_mysql_network
  queue-worker:
    container_name: surat-queue
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work --timeout=600 --tries=3
    volumes:
      - ./.env:/app/.env
      - storage_data:/app/storage
    networks:
      - default
      - mysql-stack_mysql_network

volumes:
  storage_data:

networks:
  default: {}
  mysql-stack_mysql_network:
    external: true
